//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicRegistration
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lekarz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lekarz()
        {
            this.Wizyta = new HashSet<Wizyta>();
        }

        public Lekarz(int ID, string Imie, string Nazwisko)
        {
            this.Wizyta = new HashSet<Wizyta>();
            this.ID = ID;
            this.Imie = Imie;
            this.Nazwisko = Nazwisko;
        }

        public int ID { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wizyta> Wizyta { get; set; }
    }
}
