//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicRegistration
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wizyta
    {
        public int IDLekarz { get; set; }
        public int IDSpecjalnosc { get; set; }
        public string PESEL { get; set; }
        public System.DateTime Data { get; set; }
        public System.DateTime Godzina { get; set; }
        public bool CzyWizytaOdbyta { get; set; }
    
        public virtual Lekarz Lekarz { get; set; }
        public virtual Pacjent Pacjent { get; set; }
        public virtual Specjalnosc Specjalnosc { get; set; }
    }
}
